repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff          # linter (détecte les erreurs)
        args: [--fix]     # corrige automatiquement ce qu'il peut
      - id: ruff-format   # formatter (comme black)
