"""mise_en_place_routine

Revision ID: 0375536eb44b
Revises: db5d39c28ec2
Create Date: 2026-05-27 00:10:57.056614

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0375536eb44b"
down_revision: Union[str, Sequence[str], None] = "db5d39c28ec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("routines_user_id_key"), "routines", type_="unique")
    op.drop_constraint(op.f("uq_routine_id_name"), "routines", type_="unique")
    op.create_unique_constraint(
        "uq_routine_user_id_name", "routines", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_routine_user_id_name", "routines", type_="unique")
    op.create_unique_constraint(
        op.f("uq_routine_id_name"),
        "routines",
        ["id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("routines_user_id_key"),
        "routines",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
