"""ajout des valeurs de routines

Revision ID: 417649d8e568
Revises: 72df753ee7a4
Create Date: 2026-06-05 00:36:50.706788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "417649d8e568"
down_revision: Union[str, Sequence[str], None] = "72df753ee7a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routines_values", sa.Column("date", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routines_values", "date")
    # ### end Alembic commands ###
