"""ajout contrainte uq routine_value_id_date

Revision ID: cac89dbc50df
Revises: 417649d8e568
Create Date: 2026-06-06 00:46:10.729917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac89dbc50df'
down_revision: Union[str, Sequence[str], None] = '417649d8e568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_routine_value_routine_id_date', 'routines_values', ['routine_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_routine_value_routine_id_date', 'routines_values', type_='unique')
    # ### end Alembic commands ###
