"""mise_en_place_routine

Revision ID: db5d39c28ec2
Revises: 3bdfceaf4aa9
Create Date: 2026-05-26 23:37:13.045765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db5d39c28ec2"
down_revision: Union[str, Sequence[str], None] = "3bdfceaf4aa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    routine_type_enum = sa.Enum(
        "CHECKBOX",
        "MULTISELECT",
        "TEXT",
        "FEEDBACK",
        "NUMBER",
        "TIME",
        name="routine_type",
    )
    routine_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "routines",
        sa.Column("name", sa.String(length=255), nullable=False, server_default=""),
    )
    op.add_column(
        "routines",
        sa.Column("multiselect_options", sa.JSON(), server_default="[]", nullable=True),
    )
    op.alter_column(
        "routines",
        "type",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Enum(
            "CHECKBOX",
            "MULTISELECT",
            "TEXT",
            "FEEDBACK",
            "NUMBER",
            "TIME",
            name="routine_type",
        ),
        existing_nullable=False,
        postgresql_using="type::routine_type",
    )
    op.alter_column(
        "routines",
        "tags",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.create_unique_constraint("uq_routine_id_name", "routines", ["id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_routine_id_name", "routines", type_="unique")
    op.alter_column(
        "routines",
        "tags",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.alter_column(
        "routines",
        "type",
        existing_type=sa.Enum(
            "CHECKBOX",
            "MULTISELECT",
            "TEXT",
            "FEEDBACK",
            "NUMBER",
            "TIME",
            name="routine_type",
        ),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("routines", "multiselect_options")
    op.drop_column("routines", "name")
    sa.Enum(name="routine_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
